DEBUG = True
SQLALCHEMY_DATABASE_URI = "postgres://username:password@localhost:5432/pay2ban?sslmode=disable"
SECRET_KEY = "CHANGE_ME"

TS3_USERNAME = "personalapi"
TS3_PASSWORD = "CHANGE_ME"

RECAPTCHA_SITE_KEY = "6LeWLjgUAAAAAA2Rv3LM3ONiRqaL9W14hXj3dzAt"
RECAPTCHA_SECRET_KEY = "6LeWLjgUAAAAABjqrnsLlu_IE5jw9Cj-2mqfl4d0"
SQLALCHEMY_TRACK_MODIFICATIONS = False
PROTECTED_CUI = ["coQgV9ojCUqp4hLwNa2tlHZf5Is="]
SCHEDULER_TIMEZONE = 'Europe/Copenhagen'
SCHEDULER_VIEWS_ENABLED = True
